# Default values for ovaledge.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Enter the number of pods required below
uireplicaCount: 1
jobreplicaCount: 1
esreplicaCount: 1
JAVA_OPTS: -Xms2048m -Xmx8192m


# Enter the resources allocation for ES and OE pods
# oeConfig:
#   requests:
#     memory: 6144Mi
#     cpu: "1000m"
#   limits:
#     memory: "8192Mi"
#     cpu: "2000m"

# esConfig:
#   requests:
#     memory: 4096Mi
#     cpu: 1000m
#   limits:
#     memory: 4096Mi
#     cpu: 2000m

namespace: "pf"

# Enter the image details

image:
  repository: "ovaledgellc/upwork"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "tag-v6.1.2.25.1-GA-20231207"


imagePullSecrets: [ name: regsecret ]

#kubectl create secret docker-registry regsecret --docker-server=https://index.docker.io/v1/ --docker-username=ovaledgellc --docker-password="585562e4-172c-4291-898a-2eabaf482969" --docker-email=sunitha.kotta@ovaledge.com

# Enter the SecretsManager details below

SecretsManager:
  name: 

# Enter the ServiceAccount details which the cluster uses below

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {
   }
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "ovaledge-sa"


# below are the db details required for OvalEdge. Make sure to edit the db endpoint and database name
# database given below should be loaded with scripts shared by OvalEdge team 
dbdetails:
  OVALEDGE_MYSQL_URL: "jdbc:mysql://ovaledgemysql.cqss4ijtzasl.ap-south-1.rds.amazonaws.com:3306/upwork_test?useUnicode=true&character_set_server=utf8mb4&useSSL=false&allowPublicKeyRetrieval=true"
  OVALEDGE_MYSQL_USER: "ovaledge"
  OVALEDGE_MYSQL_PWORD: "0valEdge!"
  DB_INITIAL_SIZE: "15"
  DB_MIN_IDLE: "5"
  DB_MAX_CONNECTIONS: "15"
  DB_MAX_IDLE: "10"
  READ_DB_MAX_CONNECTIONS: "15"
  READ_DB_MAX_IDLE: "10"
  DB_SPRING_MAX_CONNECTIONS: "20"

# Give your EFS filesystem Id below
EFS:
  FilesystemId: 'fs-0f4a90a01b932365d'        # Enter EFS file system id which was created earlier
  AccesspointJars: 'fsap-0d60dac35eee4ba6c'     # Enter Access point id for Jars
  AccesspointFiles: 'fsap-xxxxxxxxxxxx'   # Enter Access point id for Files
  AccesspointCerts: 'fsap-xxxxxxxxxxxx'   # Enter Access point id for Certs
  AccesspointES: 'fsap-xxxxxxxxxxxx'       # Enter Access point id for ES

# Give ElasticSearch Details below
ElasticSearch:
  ES_HOST: "oe-elasticsearch-svc"
  ES_PORT: "9200"
  ES_PROTOCOL: "http"
  ES_USER: "elastic"
  ES_PASSWORD: ""

SAML:
  SAML_METADATA_URL: ""
  ENTITY_BASE_URL: ""
  IS_LB: ""
  ENTITY_BASE_PROTOCOL: ""
  ENTITY_BASE_HOST: ""
  ENTITY_BASE_PORT: ""
  CONTEXT_PATH: ""

LDAP:
  LDAP_CUSTOM_ROLE_PREFIX: ""
  LDAP_USER_SEARCHBASE: ""
  LDAP_GROUP_SEARCHBASE: ""
  LDAP_URL: ""
  LDAP_MANAGER_DN: ""
  LDAP_MANAGER_PASSWORD: ""
  
OAUTH: 
  OAUTH2_CLIENT_ID: "clientId"
  OAUTH2_CLIENT_SECRET: "clientSecret"
  OAUTH2_BASE_URL: ""
  OAUTH2_TENANT_ID: "tenantId"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 1000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: LoadBalancer
  port: 8080

# ingress:
#   enabled: false
#   className: ""
#   annotations: {}
#     # kubernetes.io/ingress.class: nginx
#     # kubernetes.io/tls-acme: "true"
#   hosts:
#     - host: chart-example.local
#       paths:
#         - path: /
#           pathType: ImplementationSpecific
#   tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: '500m'
    memory: 2049Mi
  requests:
    cpu: '250m'
    memory: 1024Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}



