apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ElasticSearch.ES_HOST }}
  labels:
    app: oe-elasticsearch
spec:
  type: ClusterIP
  ports:
    - port: 9200
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: oe-elasticsearch