apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-files
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy:	 Retain
  storageClassName: efs-sc-generic
  csi:
    driver: efs.csi.aws.com
    volumeHandle: "{{ .Values.EFS.FilesystemId }}::{{ .Values.EFS.AccesspointFiles }}"